### ISSUE TITLE
Malformed URL for subject session info tsv

### ISSUE THREAD

**Issue by jflournoy** [FCP-INDI/rocklandsample#3]
I'm running the most recent download script using the command:

python download_rockland_raw_bids.py -o /data/rockland -v CLG2

It appears to be failing when it get's an error when trying to access the tsv containing subject session data. This is the url it appears to be trying to access:

https://s3.amazonaws.com/fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00053744/sub-A00053744_sessions.tsv

This ultimately results in a keyerror because the session_id column does not exist, only a column called <?xml version="1.0" encoding="UTF-8"?>

**Comment by jpellman** [comment]
Hi @jflournoy ,

This is because we're in the process of updating the Rockland Sample dataset in BIDS form to include participants/sessions from releases prior to release 9, so the script is hitting a file that does not exist, but which the participants.tsv file (which contains an inventory of every participant in the dataset) implies should exist.  I've uploaded the sessions TSV files for participants whose data have not yet been uploaded, and the script should now be robust to any missing NifTI files implied by the session-level directories, so your command should work now if you try it again.

**Comment by jflournoy** [comment]
Thanks @jpellman. I'm still running into a problem. Perhaps it has to do with access restrictions on the files. I've modified your code to just print out the participant.tsv file it's requesting, and the head of the participant_df (above line 154)

```
print s3_participants                                                                          
print participants_df.head() 
```

The terminal output that results is:

```
Collecting images of interest...
https://s3.amazonaws.com/fcp-indi/data/Projects/RocklandSample/RawDataBIDS/participants.tsv
              <?xml version="1.0" encoding="UTF-8"?>
0  <Error><Code>AccessDenied</Code><Message>Acces...
```

Using s3cmd, I can see the file (I've set up s3cmd to use my current aws credentials):

```
$ s3cmd ls s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/participants.tsv
2016-11-22 19:02     25705   s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/participants.tsv
```

**Comment by jpellman** [comment]
Hi @jflournoy ,

Could you try again now?
